# Generated by Django 2.2.2 on 2019-06-25 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Example',
        ),
    ]
